AWSTemplateFormatVersion: "2010-09-09"
Description: 'Sample cloudformation template to initiate EC2 instance'
Parameters: 
  KeyName: 
    Description: Name of an existing EC2 KeyPair. 
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Choose an existing EC2 KeyPair for SSH access. 
  InstanceType: 
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
    ConstraintDescription: Must be a valid ec2 instance type
    
